/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/platform-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Flags
         * @description Every flag the platform knows, on or off. A flag with no row is off and `changed_by` empty.
         *
         *     Today the only flag is the kill switch `writes_enabled` (T-23).
         */
        get: operations["get_flags_api_v1_admin_platform_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/platform-flags/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Flag
         * @description Switch a platform flag (admin). `reason` is required and may not be blank. An unknown flag
         *     name is a 404 and nothing is written.
         */
        put: operations["put_flag_api_v1_admin_platform_flags__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cases
         * @description The offense queue, newest first (architecture §24).
         *
         *     `from` and `to` bound `created_at`, `from` inclusive and `to` exclusive.
         */
        get: operations["get_cases_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case Detail
         * @description The whole case: the report, the urgent events by rank, the recommendations, the
         *     Verification, the data gaps, the evidence, the notes written and the e-mails sent.
         *
         *     The report, the Verification and the evidence are those of the evaluation whose decision the
         *     case holds (`evaluation_no` of the answer). It is the case's own number unless a
         *     re-evaluation is running or ended without a decision. A case with no report answers with
         *     what it has; an unknown `case_id` is a 404.
         */
        get: operations["get_case_detail_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback
         * @description The case's feedback, oldest first.
         */
        get: operations["get_feedback_api_v1_cases__case_id__feedback_get"];
        put?: never;
        /**
         * Post Feedback
         * @description Record the operator's verdict on the case, with the session's subject as its author.
         *
         *     The body's `case_id` must be the one in the path, otherwise 422 and nothing is written.
         */
        post: operations["post_feedback_api_v1_cases__case_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case Steps
         * @description The case's agent runs in start order (so evaluation by evaluation), each with its
         *     evaluation number and its tool calls.
         *
         *     An unknown `case_id` is a 404.
         */
        get: operations["get_case_steps_api_v1_cases__case_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/log-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Log Sources
         * @description The log sources by ID. `q` matches part of the name or the type name.
         */
        get: operations["get_log_sources_api_v1_catalog_log_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/log-sources/{log_source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Log Source
         * @description One catalog log source; an unknown ID is a 404.
         */
        get: operations["get_log_source_api_v1_catalog_log_sources__log_source_id__get"];
        /**
         * Put Log Source
         * @description An admin's edit of a log source. It becomes `defined` and the change is audited.
         */
        put: operations["put_log_source_api_v1_catalog_log_sources__log_source_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rules
         * @description The rules by ID. `q` matches part of the name; `missing` keeps what QRadar stopped listing
         *     (`missing_since` set) or only what it lists (`missing=false`) (T-37).
         */
        get: operations["get_rules_api_v1_catalog_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rule
         * @description One catalog rule; an unknown `rule_id` is a 404.
         */
        get: operations["get_rule_api_v1_catalog_rules__rule_id__get"];
        /**
         * Put Rule
         * @description An admin's edit of a rule. The rule becomes `defined` and the change is audited.
         *
         *     An unknown `rule_id` is a 404 and nothing is written.
         */
        put: operations["put_rule_api_v1_catalog_rules__rule_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rules/{rule_id}/accept-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Accept Draft
         * @description Accept the note the AI suggested: it becomes the rule's `context_note` and the draft is
         *     cleared. A rule with no draft, or an unknown `rule_id`, is a 404.
         */
        post: operations["post_accept_draft_api_v1_catalog_rules__rule_id__accept_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Sync
         * @description Start the KnowledgeSync Schedule now; Temporal runs it, and 202 says it was accepted.
         *
         *     The API itself reads nothing from QRadar. The audit row is written first and committed only
         *     when Temporal took the trigger, so a sync never starts without one. Temporal being
         *     unreachable is a 503 (`temporal.unavailable`); a Schedule the batch worker has not created
         *     yet is a 409 (`catalog.sync_not_scheduled`). Neither leaves an audit row.
         */
        post: operations["post_sync_api_v1_catalog_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/critical-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Critical Assets
         * @description The hand-kept critical asset list, by kind then value (architecture §9).
         */
        get: operations["get_critical_assets_api_v1_critical_assets_get"];
        put?: never;
        /**
         * Post Critical Asset
         * @description Add a critical asset (admin). Storage normalizes an IP or CIDR and validates the level; a
         *     value it refuses is a 422 and nothing is written.
         */
        post: operations["post_critical_asset_api_v1_critical_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/critical-assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Asset
         * @description Remove a critical asset (admin); an unknown ID is a 404 and nothing is written.
         */
        delete: operations["delete_asset_api_v1_critical_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Groups
         * @description The groups, newest window first. `from` and `to` bound `window_start`.
         */
        get: operations["get_groups_api_v1_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Group
         * @description The group, the offenses it holds, the deterministic summary and the decision of its own
         *     case.
         *
         *     The summary is counted from the group's rows (no model): the number of offenses, the time
         *     range, the rules, and for each kind of value the number of different values and the most
         *     frequent ones.
         *
         *     A group with no case yet (still being filled) answers with the group and its offenses; an
         *     unknown `group_id` is a 404.
         */
        get: operations["get_group_api_v1_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only: no authentication, no version, no database detail.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The session's subject, display name and roles, most privileged first.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sla
         * @description How the cases whose SLA deadline falls in the range met it, per `floor_level`.
         *
         *     `from` is inclusive and `to` exclusive; both are ISO 8601 with a time zone. Without a range the
         *     last day is used. The cases with no floor are the `none` bucket, and only a case's latest
         *     evaluation counts (T-63 (4)): there is no evaluation history yet. Each bucket's numbers add up
         *     to its total: on time, late, undecided (`no_ai_decision`), running, and closed in QRadar
         *     before the AI decided.
         */
        get: operations["get_sla_api_v1_metrics_sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipients
         * @description The named recipient groups and the domain allowlist that guards them (admin).
         */
        get: operations["get_recipients_api_v1_notification_recipients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-recipients/{list_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Recipients
         * @description Replace a recipient group's whole membership (admin). A new group name creates the group.
         *
         *     One address whose domain is not on the allowlist refuses the whole request: nothing is
         *     written, and the group keeps the members it had. The address's local part is kept and its
         *     domain is lowercased, so `Soc-1@EXAMPLE.COM` is stored as `Soc-1@example.com`. An empty list
         *     removes the group, unless a route names it (409 `notification_recipients.group_in_use`).
         */
        put: operations["put_recipients_api_v1_notification_recipients__list_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routes
         * @description The routing table: which alert kind and level goes to which groups (admin).
         */
        get: operations["get_routes_api_v1_notification_routes_get"];
        /**
         * Put Routes
         * @description Replace the whole routing table (admin).
         *
         *     A route to a group that has no members is refused (422) and the table keeps what it had. A
         *     case or group alert names a level and a hunt report none; another route would never match an
         *     e-mail and is a 422 as well. The replacement is one transaction, so the executor never reads a
         *     half-written table.
         */
        put: operations["put_routes_api_v1_notification_routes_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qa Queue
         * @description The QA queue across all cases, oldest first: the longest waiting item is first.
         */
        get: operations["get_qa_queue_api_v1_qa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa/{item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Qa Item Route
         * @description Resolve a QA item and record the operator's feedback for its case, in one transaction.
         *
         *     An item that is already resolved is a 409 (`qa.already_resolved`) and neither the item nor
         *     the feedback changes.
         */
        post: operations["resolve_qa_item_route_api_v1_qa__item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "investigate_further" | "contain_host_manual" | "reset_credentials_manual" | "block_ioc_manual" | "tune_rule" | "close_as_fp" | "notify_user";
        /**
         * AgentStep
         * @description One agent run of a case's steps (architecture §24, "ajan adımlarının özeti").
         */
        AgentStep: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Ended At */
            ended_at: string | null;
            /** Error */
            error?: string | null;
            /** Evaluation No */
            evaluation_no?: number | null;
            /** Model Alias */
            model_alias: string;
            /** Prompt Version */
            prompt_version: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"] | null;
            /** Tokens */
            tokens: number;
            /** Tool Call Count */
            tool_call_count: number;
        };
        /**
         * CaseDetail
         * @description `GET /cases/{case_id}`: the whole case, as architecture §24's detail screen shows it.
         */
        CaseDetail: {
            case: components["schemas"]["CaseSummary"];
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Evaluation No */
            evaluation_no: number;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Notes */
            notes?: components["schemas"]["NoteItem"][];
            /** Notifications */
            notifications?: components["schemas"]["NotificationItem"][];
            /** Recommendations */
            recommendations?: components["schemas"]["Recommendation"][];
            report?: components["schemas"]["CaseReport"] | null;
            /** Urgent Events */
            urgent_events?: components["schemas"]["UrgentEvent"][];
            verification?: components["schemas"]["VerificationResult"] | null;
        };
        /**
         * CaseReport
         * @description Case output of the Reporting agent. Turkish fields end in `_tr`.
         *
         *     `data_gaps` comes from `AgentResult`.
         */
        CaseReport: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            confidence: components["schemas"]["Confidence"];
            /** Data Gaps */
            data_gaps: components["schemas"]["DataGap"][];
            /** Injection Suspected */
            injection_suspected: boolean;
            notify_level: components["schemas"]["Level"];
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            status: components["schemas"]["RunStatus"];
            /** Summary Tr */
            summary_tr: string;
            /** Task Id */
            task_id: string;
            /** Urgent Events */
            urgent_events: components["schemas"]["UrgentEvent"][];
            usage: components["schemas"]["Usage"];
            verdict: components["schemas"]["CaseVerdict"];
        };
        /**
         * CaseSource
         * @enum {string}
         */
        CaseSource: "offense" | "hunt" | "group";
        /**
         * CaseStatus
         * @description `cases.status`.
         * @enum {string}
         */
        CaseStatus: "running" | "decided" | "no_ai_decision" | "closed";
        /**
         * CaseStep
         * @description An agent run with its calls, in the order they were recorded.
         */
        CaseStep: {
            step: components["schemas"]["AgentStep"];
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallItem"][];
        };
        /**
         * CaseSummary
         * @description One row of the offense queue (architecture §24).
         */
        CaseSummary: {
            ai_level: components["schemas"]["Level"] | null;
            /** Case Id */
            case_id: string;
            confidence: components["schemas"]["Confidence"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Evaluation No */
            evaluation_no: number;
            floor_level: components["schemas"]["Level"] | null;
            /** Group Id */
            group_id?: string | null;
            /** Hunt Id */
            hunt_id?: string | null;
            notify_level: components["schemas"]["Level"] | null;
            /** Offense Description */
            offense_description?: string | null;
            /** Offense Id */
            offense_id?: number | null;
            /** Qradar Offense Url */
            qradar_offense_url?: string | null;
            /** Rule Ids */
            rule_ids?: number[];
            /**
             * Sla Due At
             * Format: date-time
             */
            sla_due_at: string;
            /**
             * Sla Overdue
             * @default false
             */
            sla_overdue: boolean;
            source: components["schemas"]["CaseSource"];
            status: components["schemas"]["CaseStatus"];
            verdict: components["schemas"]["CaseVerdict"] | null;
        };
        /**
         * CaseVerdict
         * @enum {string}
         */
        CaseVerdict: "tp" | "fp" | "suspicious";
        /**
         * CatalogLogSource
         * @description One `catalog_log_sources` row.
         */
        CatalogLogSource: {
            /** Context Note */
            context_note: string | null;
            criticality: components["schemas"]["Level"] | null;
            /** Defined */
            defined: boolean;
            /** Description */
            description: string | null;
            /** In Scope */
            in_scope: boolean;
            /** Log Source Id */
            log_source_id: number;
            /** Missing Since */
            missing_since?: string | null;
            /** Name */
            name: string;
            /** Owner */
            owner: string | null;
            /** Type Name */
            type_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
        };
        /**
         * CatalogLogSourceUpdate
         * @description `PUT /catalog/log-sources/{log_source_id}` (admin). The log source becomes defined.
         */
        CatalogLogSourceUpdate: {
            /** Context Note */
            context_note?: string | null;
            criticality?: components["schemas"]["Level"] | null;
            /** Description */
            description?: string | null;
            /** In Scope */
            in_scope: boolean;
            /** Owner */
            owner?: string | null;
        };
        /**
         * CatalogMode
         * @enum {string}
         */
        CatalogMode: "analyze" | "skip";
        /**
         * CatalogRule
         * @description One `catalog_rules` row, as the catalog screen shows it.
         */
        CatalogRule: {
            /** Ai Draft Note */
            ai_draft_note?: string | null;
            /** Attack Techniques */
            attack_techniques?: string[];
            /** Context Note */
            context_note: string | null;
            /** Defined */
            defined: boolean;
            /** Has Automated Action */
            has_automated_action: boolean;
            min_level: components["schemas"]["Level"] | null;
            /** Missing Since */
            missing_since?: string | null;
            mode: components["schemas"]["CatalogMode"];
            /** Qradar Enabled */
            qradar_enabled: boolean;
            /** Rule Id */
            rule_id: number;
            /** Rule Name */
            rule_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string;
        };
        /**
         * CatalogRuleUpdate
         * @description `PUT /catalog/rules/{rule_id}` (admin). The rule becomes defined.
         */
        CatalogRuleUpdate: {
            /** Attack Techniques */
            attack_techniques?: string[];
            /** Context Note */
            context_note?: string | null;
            /** Has Automated Action */
            has_automated_action: boolean;
            min_level?: components["schemas"]["Level"] | null;
            mode: components["schemas"]["CatalogMode"];
        };
        /** Claim */
        Claim: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "low" | "medium" | "high";
        /**
         * CriticalAsset
         * @description One `critical_assets` row.
         */
        CriticalAsset: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["CriticalAssetKind"];
            /** Label */
            label: string;
            level: components["schemas"]["Level"];
            /** Value */
            value: string;
        };
        /**
         * CriticalAssetAdd
         * @description `POST /critical-assets` (admin). Storage normalizes and validates the value.
         */
        CriticalAssetAdd: {
            kind: components["schemas"]["CriticalAssetKind"];
            /** Label */
            label: string;
            level: components["schemas"]["Level"];
            /** Value */
            value: string;
        };
        /**
         * CriticalAssetKind
         * @description `critical_assets.kind`.
         * @enum {string}
         */
        CriticalAssetKind: "ip" | "cidr" | "host" | "user";
        /** DataGap */
        DataGap: {
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            reason: components["schemas"]["DataGapReason"];
            /** Source */
            source: string;
        };
        /**
         * DataGapReason
         * @enum {string}
         */
        DataGapReason: "no_data" | "not_parsed" | "not_visible" | "query_failed" | "budget_exhausted";
        /** Disagreement */
        Disagreement: {
            /** Claim Text */
            claim_text: string;
            /** Reason */
            reason: string;
        };
        /**
         * EmailKind
         * @enum {string}
         */
        EmailKind: "case_alert" | "group_alert" | "hunt_report";
        /**
         * EvidenceItem
         * @description One evidence row of the case detail: where to find the event at the source.
         */
        EvidenceItem: {
            /** Cited */
            cited: boolean;
            /** Evidence Id */
            evidence_id: string;
            /** Identifiers */
            identifiers: {
                [key: string]: string;
            };
            /** Query Hash */
            query_hash: string;
            /** Query Text */
            query_text: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            source: components["schemas"]["EvidenceSource"];
            /**
             * Time End
             * Format: date-time
             */
            time_end: string;
            /**
             * Time Start
             * Format: date-time
             */
            time_start: string;
            /**
             * Tool Id
             * @default
             */
            tool_id: string;
        };
        /**
         * EvidenceSource
         * @enum {string}
         */
        EvidenceSource: "qradar" | "falcon";
        /**
         * FeedbackAnswer
         * @description `POST /cases/{case_id}/feedback`: the stored feedback, with who wrote it.
         */
        FeedbackAnswer: {
            /** Case Id */
            case_id: string;
            /** Comment */
            comment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            reason: components["schemas"]["FeedbackReason"];
            /** User Subject */
            user_subject: string;
            verdict: components["schemas"]["CaseVerdict"];
        };
        /**
         * FeedbackReason
         * @enum {string}
         */
        FeedbackReason: "correct" | "was_tp_not_fp" | "was_fp_not_tp" | "missing_context" | "wrong_urgent_events" | "other";
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * FullAnalysisReason
         * @description `offenses_seen.full_analysis_reason`: why an offense of a group got a full analysis
         *     (architecture §9; T-14, T-22, T-62). Not in data-model.md (T-027). Empty for an offense the
         *     group took, a skipped one and one recorded before the column existed.
         *
         *     The hourly limit counts `limit` and `exempt`; `novelty` and `sample` have counters of their
         *     own, so they do not use up the limit.
         * @enum {string}
         */
        FullAnalysisReason: "limit" | "exempt" | "novelty" | "sample";
        /**
         * GroupDetail
         * @description `GET /groups/{group_id}`: the group, its offenses and its evaluation's decision.
         */
        GroupDetail: {
            /** Case Id */
            case_id?: string | null;
            case_status?: components["schemas"]["CaseStatus"] | null;
            group: components["schemas"]["GroupSummary"];
            notify_level?: components["schemas"]["Level"] | null;
            /** Offenses */
            offenses?: components["schemas"]["GroupOffense"][];
            report?: components["schemas"]["CaseReport"] | null;
            summary: components["schemas"]["GroupDigest"];
            verdict?: components["schemas"]["CaseVerdict"] | null;
        };
        /**
         * GroupDigest
         * @description The deterministic summary of a group, counted from its rows (T-029 criterion 9; no model).
         */
        GroupDigest: {
            /** First Seen At */
            first_seen_at?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Offense Count */
            offense_count: number;
            /** Rule Ids */
            rule_ids?: number[];
            /** Values */
            values?: components["schemas"]["GroupValueKindSummary"][];
        };
        /**
         * GroupOffense
         * @description One offense of a group.
         */
        GroupOffense: {
            /** Case Id */
            case_id?: string | null;
            /** Description */
            description: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            full_analysis_reason?: components["schemas"]["FullAnalysisReason"] | null;
            /** Offense Id */
            offense_id: number;
            /** Qradar Offense Url */
            qradar_offense_url?: string | null;
            status: components["schemas"]["OffenseStatus"];
        };
        /**
         * GroupStatus
         * @description `offense_groups.status`.
         * @enum {string}
         */
        GroupStatus: "open" | "storm" | "closed";
        /**
         * GroupSummary
         * @description One row of the group list.
         */
        GroupSummary: {
            /** Case Id */
            case_id?: string | null;
            /** Group Id */
            group_id: string;
            /** Offense Count */
            offense_count: number;
            /** Rule Set Hash */
            rule_set_hash: string;
            status: components["schemas"]["GroupStatus"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /**
         * GroupValueCount
         * @description One value of a group and the number of its offenses that carry it.
         */
        GroupValueCount: {
            /** Offenses */
            offenses: number;
            /** Value */
            value: string;
        };
        /**
         * GroupValueKind
         * @description `offense_group_values.kind`: the values a group keeps of its offenses (T-46, T-62).
         *     Not in data-model.md (T-027).
         * @enum {string}
         */
        GroupValueKind: "source_ip" | "destination_ip" | "username" | "log_source" | "category";
        /**
         * GroupValueKindSummary
         * @description One kind of value (source IP, user, log source, ...) over the group's offenses.
         */
        GroupValueKindSummary: {
            /** Distinct */
            distinct: number;
            kind: components["schemas"]["GroupValueKind"];
            /** Top */
            top?: components["schemas"]["GroupValueCount"][];
        };
        /**
         * Health
         * @description `GET /health`: liveness only. No version, no database detail, no settings.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * Level
         * @description Severity level. Values compare as strings, not by severity.
         * @enum {string}
         */
        Level: "low" | "medium" | "high" | "critical";
        /**
         * Me
         * @description `GET /me`: who the session is and what it may do.
         */
        Me: {
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Subject */
            subject: string;
        };
        /**
         * NoteItem
         * @description One `notes_written` row: what the executor did with the QRadar note.
         */
        NoteItem: {
            /** Error */
            error: string | null;
            /** Evaluation No */
            evaluation_no: number;
            /** Offense Id */
            offense_id: number;
            /** Run Marker */
            run_marker: string;
            status: components["schemas"]["NoteStatus"];
            /**
             * Written At
             * Format: date-time
             */
            written_at: string;
        };
        /**
         * NoteStatus
         * @description `notes_written.status`.
         *
         *     `disabled`: the kill switch was off (shadow mode, T-23), so the note was not written. It is
         *     not a failure; the error alarms do not count it (T-37).
         * @enum {string}
         */
        NoteStatus: "written" | "skipped_duplicate" | "disabled" | "failed";
        /**
         * NotificationItem
         * @description One `notifications` row: the alert e-mail and what became of it.
         */
        NotificationItem: {
            /** Error */
            error: string | null;
            kind: components["schemas"]["EmailKind"];
            level: components["schemas"]["Level"] | null;
            /** Recipients */
            recipients: string[];
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["NotificationStatus"];
            /** Subject */
            subject: string;
        };
        /**
         * NotificationRoute
         * @description One `notification_routes` row: an alert kind and level go to these groups.
         */
        NotificationRoute: {
            kind: components["schemas"]["EmailKind"];
            level?: components["schemas"]["Level"] | null;
            /** List Name */
            list_name: string;
        };
        /**
         * NotificationRouteEntry
         * @description One route of `PUT /notification-routes`.
         *
         *     A case or group alert is routed by its level, a hunt report without one. A route that breaks
         *     this would never match an e-mail the executor sends, so it is a 422 rather than a dead row.
         *     The check is on the request only: a row already stored is shown as it is, so an admin can
         *     see and replace it.
         */
        NotificationRouteEntry: {
            kind: components["schemas"]["EmailKind"];
            level?: components["schemas"]["Level"] | null;
            /** List Name */
            list_name: string;
        };
        /**
         * NotificationRoutesUpdate
         * @description `PUT /notification-routes` (admin): the whole table, every kind and level included.
         */
        NotificationRoutesUpdate: {
            /** Routes */
            routes: components["schemas"]["NotificationRouteEntry"][];
        };
        /**
         * NotificationStatus
         * @description `notifications.status`.
         *
         *     `disabled`: the kill switch was off (T-23), so the e-mail was not sent. Only `sent` counts
         *     as sent; a key recorded as `disabled`, `rejected` or `failed` is tried again (T-37).
         * @enum {string}
         */
        NotificationStatus: "sent" | "rejected" | "disabled" | "failed";
        /**
         * OffenseStatus
         * @description `offenses_seen.status`.
         * @enum {string}
         */
        OffenseStatus: "pending" | "running" | "done" | "skipped" | "grouped";
        /** OperatorFeedback */
        OperatorFeedback: {
            /** Case Id */
            case_id: string;
            /** Comment */
            comment?: string | null;
            reason: components["schemas"]["FeedbackReason"];
            verdict: components["schemas"]["CaseVerdict"];
        };
        /** Page[CaseSummary] */
        Page_CaseSummary_: {
            /** Items */
            items: components["schemas"]["CaseSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[CatalogLogSource] */
        Page_CatalogLogSource_: {
            /** Items */
            items: components["schemas"]["CatalogLogSource"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[CatalogRule] */
        Page_CatalogRule_: {
            /** Items */
            items: components["schemas"]["CatalogRule"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[GroupSummary] */
        Page_GroupSummary_: {
            /** Items */
            items: components["schemas"]["GroupSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[QAItemSummary] */
        Page_QAItemSummary_: {
            /** Items */
            items: components["schemas"]["QAItemSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * PlatformFlag
         * @description `platform_flags.name`: the switches the platform knows (T-23).
         * @enum {string}
         */
        PlatformFlag: "writes_enabled";
        /**
         * PlatformFlagState
         * @description `GET /admin/platform-flags`: every known flag. A flag with no row is off.
         */
        PlatformFlagState: {
            /** Changed At */
            changed_at?: string | null;
            /** Changed By */
            changed_by?: string | null;
            /** Enabled */
            enabled: boolean;
            name: components["schemas"]["PlatformFlag"];
            /** Reason */
            reason?: string | null;
        };
        /**
         * PlatformFlagUpdate
         * @description `PUT /admin/platform-flags/{name}` (admin). `reason` is required and may not be blank.
         */
        PlatformFlagUpdate: {
            /** Enabled */
            enabled: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * PolicyDecision
         * @description `tool_calls.policy_decision`.
         * @enum {string}
         */
        PolicyDecision: "allow" | "deny";
        /**
         * Problem
         * @description The shape of an RFC 9457 answer, for the UI's own error handling.
         *
         *     Not a response model of any route: `ais0c_api.openapi` makes it every operation's `default`
         *     response in the schema. `errors`, `domains` and `list_names` appear only on the problems that
         *     carry them.
         */
        Problem: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Domains
             * @default null
             */
            domains: string[] | null;
            /**
             * Errors
             * @default null
             */
            errors: components["schemas"]["FieldError"][] | null;
            /**
             * List Names
             * @default null
             */
            list_names: string[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * QAItemSummary
         * @description One row of the QA queue.
         */
        QAItemSummary: {
            /** Case Id */
            case_id: string;
            case_notify_level?: components["schemas"]["Level"] | null;
            case_status?: components["schemas"]["CaseStatus"] | null;
            /** Case Summary Tr */
            case_summary_tr?: string | null;
            case_verdict?: components["schemas"]["CaseVerdict"] | null;
            /** Evaluation No */
            evaluation_no: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            reason: components["schemas"]["QAReason"];
            /** Resolved At */
            resolved_at: string | null;
            /** Resolved By */
            resolved_by: string | null;
            status: components["schemas"]["QAStatus"];
        };
        /**
         * QAReason
         * @enum {string}
         */
        QAReason: "random_sample" | "verifier_conflict" | "injection_suspected" | "low_confidence" | "fp_with_data_gap";
        /**
         * QAResolveAnswer
         * @description The resolved item and the feedback it wrote for the case.
         */
        QAResolveAnswer: {
            feedback: components["schemas"]["FeedbackAnswer"];
            item: components["schemas"]["QAItemSummary"];
        };
        /**
         * QAResolveRequest
         * @description `POST /qa/{id}/resolve`: the operator's verdict, reason and optional comment.
         */
        QAResolveRequest: {
            /** Comment */
            comment?: string | null;
            reason: components["schemas"]["FeedbackReason"];
            verdict: components["schemas"]["CaseVerdict"];
        };
        /**
         * QAStatus
         * @description `qa_items.status`.
         * @enum {string}
         */
        QAStatus: "open" | "resolved";
        /**
         * RecipientGroup
         * @description One named recipient group and its members (D-41).
         */
        RecipientGroup: {
            /** Emails */
            emails: string[];
            /** List Name */
            list_name: string;
        };
        /**
         * RecipientGroupUpdate
         * @description `PUT /notification-recipients/{list_name}` (admin): the group's whole membership.
         */
        RecipientGroupUpdate: {
            /** Emails */
            emails: string[];
        };
        /**
         * RecipientsView
         * @description `GET /notification-recipients`: the groups and the domain allowlist that guards them.
         */
        RecipientsView: {
            /** Allowed Domains */
            allowed_domains: string[];
            /** Groups */
            groups: components["schemas"]["RecipientGroup"][];
        };
        /** Recommendation */
        Recommendation: {
            action_type: components["schemas"]["ActionType"];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Rationale */
            rationale: string;
            /** Target */
            target: string;
        };
        /**
         * Role
         * @description `api.md`'s three roles, least to most.
         * @enum {string}
         */
        Role: "operator" | "hunter" | "admin";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "completed" | "budget_exhausted" | "failed";
        /**
         * SLAMetrics
         * @description `GET /metrics/sla`: how the cases with a deadline in the range met it.
         */
        SLAMetrics: {
            /** Buckets */
            buckets: components["schemas"]["SlaRow"][];
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /**
         * SlaRow
         * @description One `floor_level` bucket of `GET /metrics/sla`; the numbers add up to `total`.
         */
        SlaRow: {
            /** Closed */
            closed: number;
            /** Floor Level */
            floor_level: "none" | components["schemas"]["Level"];
            /** Late */
            late: number;
            /** On Time */
            on_time: number;
            /** Running */
            running: number;
            /** Total */
            total: number;
            /** Undecided */
            undecided: number;
        };
        /**
         * SyncAccepted
         * @description `POST /catalog/sync`: the Schedule was triggered; the run itself is Temporal's.
         */
        SyncAccepted: {
            /** Schedule Id */
            schedule_id: string;
            /**
             * Triggered
             * @default true
             * @constant
             */
            triggered: true;
        };
        /**
         * ToolCallItem
         * @description One gateway call of an agent run: the policy decision and how long it took.
         */
        ToolCallItem: {
            /** Deny Reason */
            deny_reason: string | null;
            /** Evidence Id */
            evidence_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            policy_decision: components["schemas"]["PolicyDecision"];
            status: components["schemas"]["ToolStatus"];
            /** Tool Id */
            tool_id: string;
        };
        /**
         * ToolStatus
         * @enum {string}
         */
        ToolStatus: "ok" | "denied" | "error";
        /**
         * UrgentEvent
         * @description An event the operator should look at first (architecture §9).
         */
        UrgentEvent: {
            /** Aql */
            aql?: string | null;
            /** Checklist */
            checklist: string[];
            /** Destination */
            destination?: string | null;
            /** Event Name */
            event_name: string;
            /** Evidence Id */
            evidence_id: string;
            /** Log Source */
            log_source: string;
            /** Qid */
            qid?: number | null;
            /** Rank */
            rank: number;
            /** Reason */
            reason: string;
            /** Source */
            source?: string | null;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Username */
            username?: string | null;
        };
        /** Usage */
        Usage: {
            /** Seconds */
            seconds: number;
            /** Tokens */
            tokens: number;
            /** Tool Calls */
            tool_calls: number;
        };
        /** VerificationResult */
        VerificationResult: {
            /** Agrees */
            agrees: boolean;
            /** Checked Evidence Ids */
            checked_evidence_ids: string[];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            confidence: components["schemas"]["Confidence"];
            /** Data Gaps */
            data_gaps: components["schemas"]["DataGap"][];
            /** Disagreements */
            disagreements: components["schemas"]["Disagreement"][];
            /** Injection Suspected */
            injection_suspected: boolean;
            status: components["schemas"]["RunStatus"];
            /** Task Id */
            task_id: string;
            usage: components["schemas"]["Usage"];
            verdict: components["schemas"]["CaseVerdict"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_flags_api_v1_admin_platform_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformFlagState"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_flag_api_v1_admin_platform_flags__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformFlagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformFlagState"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"][] | null;
                notify_level?: components["schemas"]["Level"][] | null;
                verdict?: components["schemas"]["CaseVerdict"][] | null;
                source?: components["schemas"]["CaseSource"][] | null;
                rule_id?: number[] | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CaseSummary_"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_case_detail_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_feedback_api_v1_cases__case_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackAnswer"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    post_feedback_api_v1_cases__case_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackAnswer"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_case_steps_api_v1_cases__case_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseStep"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_log_sources_api_v1_catalog_log_sources_get: {
        parameters: {
            query?: {
                defined?: boolean | null;
                in_scope?: boolean | null;
                missing?: boolean | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CatalogLogSource_"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_log_source_api_v1_catalog_log_sources__log_source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogLogSource"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_log_source_api_v1_catalog_log_sources__log_source_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogLogSourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogLogSource"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_rules_api_v1_catalog_rules_get: {
        parameters: {
            query?: {
                defined?: boolean | null;
                mode?: components["schemas"]["CatalogMode"] | null;
                qradar_enabled?: boolean | null;
                missing?: boolean | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CatalogRule_"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_rule_api_v1_catalog_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogRule"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_rule_api_v1_catalog_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogRule"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    post_accept_draft_api_v1_catalog_rules__rule_id__accept_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogRule"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    post_sync_api_v1_catalog_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_critical_assets_api_v1_critical_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalAsset"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    post_critical_asset_api_v1_critical_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriticalAssetAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalAsset"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_asset_api_v1_critical_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_groups_api_v1_groups_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["GroupStatus"][] | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupSummary_"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_group_api_v1_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetail"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_sla_api_v1_metrics_sla_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLAMetrics"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_recipients_api_v1_notification_recipients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientsView"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_recipients_api_v1_notification_recipients__list_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientGroup"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_routes_api_v1_notification_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRoute"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_routes_api_v1_notification_routes_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRoutesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRoute"][];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_qa_queue_api_v1_qa_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["QAStatus"][] | null;
                reason?: components["schemas"]["QAReason"][] | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_QAItemSummary_"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resolve_qa_item_route_api_v1_qa__item_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QAResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAResolveAnswer"];
                };
            };
            /** @description An RFC 9457 problem. `title` is a machine-readable code (`catalog.rule_not_found`); the UI builds the message from it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
