"""Pydantic schemas shared by every ais0c package; the single source of truth.

Defined in docs/impl/contracts.md. No business logic and no I/O.
"""

from ais0c_contracts.agents import (
    AgentResult,
    AgentTask,
    CasePlan,
    CaseReport,
    Disagreement,
    InvestigationHypothesis,
    InvestigationResult,
    PlanStep,
    TimelineEntry,
    TriageResult,
    VerificationResult,
)
from ais0c_contracts.common import (
    RUN_ID_MAX_LENGTH,
    SHORT_TEXT_MAX_LENGTH,
    SUMMARY_MAX_LENGTH,
    AttackTechnique,
    Budget,
    Claim,
    ContractModel,
    DataGap,
    EvidenceId,
    EvidenceRef,
    Recommendation,
    RunId,
    ShortText,
    Summary,
    TimeWindow,
    UrgentEvent,
    Usage,
    UtcDatetime,
)
from ais0c_contracts.enums import (
    ActionType,
    CaseSource,
    CaseVerdict,
    CatalogMode,
    Confidence,
    CostClass,
    DataGapReason,
    EmailKind,
    EvidenceSource,
    FeedbackReason,
    HuntOutcome,
    Level,
    QAReason,
    RunStatus,
    ToolStatus,
    TuningChange,
)
from ais0c_contracts.executor import EmailMessage, NoteContent
from ais0c_contracts.hunt import (
    MAX_HUNT_WINDOW_MONTHS,
    CoverageEntry,
    DetectionProposal,
    HuntReport,
    HuntRequest,
    HuntScope,
    HuntVersions,
    HypothesisResult,
    derive_hunt_outcome,
)
from ais0c_contracts.offense import (
    CatalogContext,
    CatalogLogSource,
    CatalogRule,
    CriticalAssetHit,
    EnrichmentContext,
    EntityResolution,
    IocHit,
    OffenseSnapshot,
)
from ais0c_contracts.registry import ModelRelease, SkillRef
from ais0c_contracts.tools import ToolCoverage, ToolIntent, ToolResult
from ais0c_contracts.tuning import Backtest, OperatorFeedback, TuningProposal

__all__ = [
    "MAX_HUNT_WINDOW_MONTHS",
    "RUN_ID_MAX_LENGTH",
    "SHORT_TEXT_MAX_LENGTH",
    "SUMMARY_MAX_LENGTH",
    "ActionType",
    "AgentResult",
    "AgentTask",
    "AttackTechnique",
    "Backtest",
    "Budget",
    "CasePlan",
    "CaseReport",
    "CaseSource",
    "CaseVerdict",
    "CatalogContext",
    "CatalogLogSource",
    "CatalogMode",
    "CatalogRule",
    "Claim",
    "Confidence",
    "ContractModel",
    "CostClass",
    "CoverageEntry",
    "CriticalAssetHit",
    "DataGap",
    "DataGapReason",
    "DetectionProposal",
    "Disagreement",
    "EmailKind",
    "EmailMessage",
    "EnrichmentContext",
    "EntityResolution",
    "EvidenceId",
    "EvidenceRef",
    "EvidenceSource",
    "FeedbackReason",
    "HuntOutcome",
    "HuntReport",
    "HuntRequest",
    "HuntScope",
    "HuntVersions",
    "HypothesisResult",
    "InvestigationHypothesis",
    "InvestigationResult",
    "IocHit",
    "Level",
    "ModelRelease",
    "NoteContent",
    "OffenseSnapshot",
    "OperatorFeedback",
    "PlanStep",
    "QAReason",
    "Recommendation",
    "RunId",
    "RunStatus",
    "ShortText",
    "SkillRef",
    "Summary",
    "TimeWindow",
    "TimelineEntry",
    "ToolCoverage",
    "ToolIntent",
    "ToolResult",
    "ToolStatus",
    "TriageResult",
    "TuningChange",
    "TuningProposal",
    "UrgentEvent",
    "Usage",
    "UtcDatetime",
    "VerificationResult",
    "derive_hunt_outcome",
]
