[tox]
envlist=py3-{analyse,test}
toxworkdir=./.tox

[testenv]
setenv =
    install_command=python -m pip install
    TOX_PACKAGE_NAME="qradar_mcp"
    PYTEST_COV_REPORT_FILE=./coverage-reports/coverage-results-py3.xml
    PYTEST_XUNIT_REPORT_FILE=./xunit-reports/xunit-result-qradarmcp.xml
whitelist_externals =
    rm
    mkdir

envdir = {toxworkdir}/py3

alwayscopy = true

sitepackages=False

usedevelop=true

passenv=
    CI_*

deps = -rdev_requirements.txt

commands =
    analyse: python -m pylint --ignore=tests --rcfile=pyproject.toml {env:TOX_PACKAGE_NAME}
    test: python -m pytest -n 5 --cov={env:TOX_PACKAGE_NAME} --cov-report=term \
    test:    --cov-report=html --cov-report=xml:{env:PYTEST_COV_REPORT_FILE} \
    test:    -o junit_family=xunit1 --junitxml={env:PYTEST_XUNIT_REPORT_FILE} \
    test:    --verbose {posargs:tests}
